name: sharmanka

services:
  sharmanka:
    build: .
    container_name: sharmanka_bot
    restart: unless-stopped
    env_file:
      - .env
    # volumes:
    #   - ./cookies.txt:/app/cookies.txt:ro

